ALTER TABLE "User"
ADD COLUMN "passwordHash" TEXT NOT NULL DEFAULT '',
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "User"
ALTER COLUMN "passwordHash" DROP DEFAULT,
ALTER COLUMN "isActive" DROP DEFAULT;
